### ISSUE TITLE
Does the program need the "make install" command during compilation?

### ISSUE THREAD

**Issue by joaofavoretti** [courselab/snaskii21#288]
I have noticed that the command `make` creates the ELF file "ttsnake" inside the src folder. Therefore It is enough to run the program in development mode.

But inside the README.md file, it says about the necessity of using:

```
make
**sudo make install**
```

As it was required to install to program with root user permissions, while it is actually not. `make install` is just required to copy the executable and its dependencies to some system directories and that is why it needs root privileges.

Lmk if I am mistaken. But I think that such information should be much clearer inside the README.md file, super user privileges is not something that you should run without any precaution.

**Comment by leonrossi** [comment]
Hello, @joaofavoretti! I tested it now by deleting all resources from the repository and trying to run just ```make``` and it really runs without errors but i can't get out of the menu, just hit the "q" button to exit the game, other commands don't work. So, in my case, ```sudo make install``` was needed to get everything running perfectly. I'm using Linux Mint 19.1. 

Maybe it's a personal problem because I'm the only one who reproduced this, but here's the notification.

**Comment by joaofavoretti** [comment]
Really @leonrossi? Have you though about how would that make sense?

**Comment by leonrossi** [comment]
I totally agree with your point, even I was surprised about the failure without using the superuser and I understand your explanation. If there's a way to change this that would be great! 
I just left my point for failure consideration without what's in the README, because you said that is enough to run the program in development mode just with the ```make```, right? I was not able to test the entire game, for example, without the install part. That was my consideration.

**Comment by joaofavoretti** [comment]
Yeah!! Sure, that is totally fine. I just got confused by that issue. I may try it latter on.

**Comment by joaofavoretti** [comment]
I don't know about that error that you have. But I have tried to install using another machine and I realized that some essential files need to be installed system wise so that the executable can run without any trouble.

The error message that I got was:
```
$ ./src/ttsnake.bin
tsnake.c: 207: read_scenes: No such file or directory
```

So yeah, besides reinforcing that we should create some way to install the program locally, without any super user permissions, this Issue is wrong. So I'll close it.
