### ISSUE TITLE
Unable to start the game on WSL

### ISSUE THREAD

**Issue by jufantozzi** [courselab/snaskii21#4]
### Bug Description

After building and bootstraping the game, I'm unable to pass through the menu screen by pressing `p` (or even generate any other behaviour from pressing other keys). I am able though, to quit through `q`.

I haven't had the chance to test on a native system yet. but I'm assuming it works? Some confirmation on this would be valuable.

### Additional Information

Running Ubuntu 20.04 on WLS2, Windows 10 20H2 19042.1288

**Comment by Dauboau** [comment]
I have actually experienced the exact same issue running the game in a Ubuntu 20.04 virtual machine in Mac OS Monterey.

**Comment by math-araujo** [comment]
I believe this is due to the `user_input` function on `ttsnake.c` file, specifically on [line 336](https://github.com/courselab/snaskii21/blob/develop/src/ttsnake.c#L336). Currently, there's no implementation for other keys besides the `q` key (to quit the game).

**Comment by jufantozzi** [comment]
I don't think issues should be closed until a PR that fixes it gets merged.

**Comment by math-araujo** [comment]
> I don't think issues should be closed until a PR that fixes it gets merged.

I would suggest to rename the issue and it's description, or creating a new issue. Contrary to what's described in the current issue, the problem is not with WSL.

**Comment by di-press** [comment]
Hello guys!

I agree that a new issue should be reopen, or have a edited description, since the description/title of the issue is not intuitive to others whom are trying to contribute to this repository. The issue is that the code to handle the user interaction is not implement yet, and not a specific problem to the WSL.

**Comment by di-press** [comment]
Hello guys!

I agree that a new issue should be reopen, or have a edited description, since the description/title of the issue is not intuitive to others whom are trying to contribute to this repository. The issue is that the code to handle the user interaction is not implement yet, and not a specific problem to the WSL.
